### ISSUE TITLE
Checklist Basics 37c3

### ISSUE THREAD

**Issue by phlmn** [bugbakery/transcribee-voctomix-glue#1]
- [ ] https://github.com/bugbakery/transcribee/issues/419
- [ ] create transcribee documents
- [ ] button to open transcribee document (via share token)
- [ ] server side export
- [ ] transcript post-processing before pushing to voctoweb (adapt to styleguide)
- [ ] push draft transcript in voctoweb pumpen (after automatic transcription)
- [ ] button to push updated transcripts to voctoweb
